#---------------------------------------------------------------------
# Initialization
#---------------------------------------------------------------------
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus
# setopt VI

#---------------------------------------------------------------------
# Functions
#---------------------------------------------------------------------

# FZF dependent functions START
if [ -x "$(command -v fzf)" ]; then

  # FZF wrapper to set color scheme
  function fzf() {
    ( # run in subshell to not pollute top level shell environment
      if [ "$SHELL" != "/bin/sh" ]; then
        # This file is symlinked to current fzf color scheme
        export FZF_DEFAULT_OPTS_FILE=~/.config/fzf/fzfrc
      fi
      $(whence -p fzf) "$@"
    )
  }

  # FZF key bindings initialization
  eval "$(fzf --zsh)"
fi
# FZF dependent functions END

# Configures ls colors
export LSCOLORS="exfxcxdxbxAxAxBxBxExEx"
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=1;30:cd=1;30:su=1;31:sg=1;31:tw=1;34:ow=1;34"

# 1Password plugins initialization
if [ -f ~/.config/op/plugins.sh ]; then
  # shellcheck disable=SC1090
  source ~/.config/op/plugins.sh
fi

# Adds Anthropics API key to environment for avante.nvim
export ANTHROPIC_API_KEY
ANTHROPIC_API_KEY="$([ -f /run/secrets/anthropic/api_key ] && cat /run/secrets/anthropic/api_key)"

# Adds Tavily API key to environment for avante.nvim
export TAVILY_API_KEY
TAVILY_API_KEY="$([ -f /run/secrets/tavily/api_key ] && cat /run/secrets/tavily/api_key)"

#---------------------------------------------------------------------
# zsh-autosuggestions
#---------------------------------------------------------------------
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

#---------------------------------------------------------------------
# zsh-history-substring-search
#---------------------------------------------------------------------
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="$(cat ~/.config/zsh/zsh-hist-sub-theme)"

# Create a function to update the highlight color without restarting the shell
update_history_highlight() {
  HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="$(cat ~/.config/zsh/zsh-hist-sub-theme)"
}
history-substring-search-up-wrap() {
  update_history_highlight
  zle history-substring-search-up
}
zle -N history-substring-search-up-wrap
history-substring-search-down-wrap() {
  update_history_highlight
  zle history-substring-search-down
}
zle -N history-substring-search-down-wrap
bindkey '^[[A' history-substring-search-up-wrap
bindkey '^[[B' history-substring-search-down-wrap

#---------------------------------------------------------------------
# zsh built-in completion menu
#---------------------------------------------------------------------
# To select previous completion
bindkey '^[[Z' reverse-menu-complete

#---------------------------------------------------------------------
# zsh theme
#---------------------------------------------------------------------
fzf-completion-wrap() {
  # shellcheck disable=SC1090
  [ -f ~/.config/zsh/zsh-theme-theme ] && source ~/.config/zsh/zsh-theme-theme
  zle fzf-completion
}
zle -N fzf-completion-wrap
bindkey '^I' fzf-completion-wrap

#---------------------------------------------------------------------
# grep theme
#---------------------------------------------------------------------
function grep() {
  ( # run in subshell to not pollute top level shell environment
    if [ "$SHELL" != "/bin/sh" ]; then
      # This file is symlinked to current fzf color scheme
      export GREP_COLORS="$(cat ~/.config/grep/grep-theme)"
    fi
    $(whence -p grep) "$@"
  )
}
