keys:
  - &Nicks-MacBook-Air-0 age1n8fm4y5rddnustnkuuvlsqy47ruatq30df73ucm6rjvsw9fjdfvs57vkf4
  - &Nicks-Mac-mini-0 age1ezk409k4wdtw8p88zqlsjq8wyst5vwt8u9taxkcrn5qy0jzw3ulqedn0ks
  - &Server-x240-0 age1hy4qq0gpr59tmsvluxjqssj8z98an6ma2rvehncvksan79pzlc7sy5635j
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *Nicks-MacBook-Air-0
          - *Nicks-Mac-mini-0
  - path_regex: secrets/Server-x240-0/secrets\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *Server-x240-0
