# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "wl" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  nixpkgs.config.permittedInsecurePackages = [
    "broadcom-sta-6.30.223.271-59-6.18.43"
    "broadcom-sta-6.30.223.271-63-6.18.41"
  ];




  fileSystems."/" =
    { device = "/dev/mapper/luks-55080c20-1b50-4a47-a99c-78db67482bc7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-55080c20-1b50-4a47-a99c-78db67482bc7".device = "/dev/disk/by-uuid/55080c20-1b50-4a47-a99c-78db67482bc7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6D4D-AB1A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3f43ec5d-e1b1-4e37-b8a5-3eef888b9d29"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

